import { Router } from 'express';
import { db, DEFAULT_SETTINGS, setSetting } from '../db.js';
import { audit } from '../lib/audit.js';
import { applyGrid, facet } from '../lib/grid.js';
import { prettyPeriod } from '../lib/cycles.js';
import { toCsv, sendCsv, describeFilters } from '../lib/csv.js';
import { requireAdmin, requireAdminOrAuditor } from '../middleware/auth.js';

/** SPEC 6.19 Analytics · 6.20 Audit Log · 6.21 System Settings. */
export const router = Router();
router.use(requireAdminOrAuditor);

const CLOSED = `('Closed','Tallied','TieNeedsDecision','Published')`;

/* ============================================================ 6.20 Audit */

const AUDIT_BASE = `
  SELECT a.id, a.occurred_at, a.actor_role, a.ip_address, a.user_agent, a.action,
         a.entity_type, a.entity_id, a.before_json, a.after_json,
         COALESCE(e.full_name, 'System') AS actor_name
    FROM audit_log a LEFT JOIN employees e ON e.id = a.actor_id`;
const AUDIT_COLUMNS = {
  occurred_at: 'a.occurred_at', actor_name: "COALESCE(e.full_name, 'System')", actor_role: 'a.actor_role',
  action: 'a.action', entity_type: 'a.entity_type', entity_id: 'a.entity_id', ip_address: 'a.ip_address',
};

router.get('/audit', (req, res) => {
  const out = applyGrid({
    base: AUDIT_BASE, columns: AUDIT_COLUMNS, query: req.query,
    defaultSort: { column: 'occurred_at', dir: 'desc' },
  });
  out.facets = { entity_type: facet(AUDIT_BASE, {}, 'entity_type'), actor_role: facet(AUDIT_BASE, {}, 'actor_role') };
  res.json(out);
});

router.get('/audit.csv', (req, res) => {
  const { rows } = applyGrid({
    base: AUDIT_BASE, columns: AUDIT_COLUMNS, query: { ...req.query, page: 1, pageSize: 100000 },
    defaultSort: { column: 'occurred_at', dir: 'desc' }, maxPageSize: 100000,
  });
  audit(req, 'report.exported', { entityType: 'report', entityId: 'audit_log', after: { rows: rows.length } });
  sendCsv(res, `audit-log-${new Date().toISOString().slice(0, 10)}.csv`, toCsv({
    meta: [['Employee Appreciation Portal — Audit Log', ''], ['Generated by', req.user.full_name],
      ['Generated at (UTC)', new Date().toISOString()], ['Filters', describeFilters(req.query)], ['Rows', rows.length]],
    rows,
    columns: [
      { label: 'Timestamp (UTC)', key: 'occurred_at' }, { label: 'Actor', key: 'actor_name' },
      { label: 'Role', key: 'actor_role' }, { label: 'Action', key: 'action' },
      { label: 'Entity Type', key: 'entity_type' }, { label: 'Entity', key: 'entity_id' },
      { label: 'IP Address', key: 'ip_address' }, { label: 'Before', key: 'before_json' }, { label: 'After', key: 'after_json' },
    ],
  }));
});

/* ========================================================= 6.21 Settings */

// Approved policy decisions (SPEC §18). Shown, never editable here.
const LOCKED = ['allow_self_vote', 'allow_edit_until_close', 'results_visibility'];
const ENUMS = {
  eoy_candidate_pool: ['all', 'monthly_winners_only'],
  winners_report_visibility: ['all_employees', 'admin_only'],
  winners_report_default_date_basis: ['announced_on', 'period'],
};

router.get('/settings', (_req, res) => {
  const rows = db.prepare(
    `SELECT s.key, s.value, s.value_type, s.updated_at, e.full_name AS updated_by
       FROM settings s LEFT JOIN employees e ON e.id = s.updated_by ORDER BY s.key`
  ).all();
  res.json({
    settings: rows.map((r) => ({
      ...r, locked: LOCKED.includes(r.key), default: DEFAULT_SETTINGS[r.key], options: ENUMS[r.key] || null,
    })),
  });
});

router.put('/settings/:key', requireAdmin, (req, res) => {
  const key = req.params.key;
  const row = db.prepare('SELECT * FROM settings WHERE key = ?').get(key);
  if (!row) return res.status(404).json({ error: 'not_found' });
  if (LOCKED.includes(key)) {
    return res.status(409).json({ error: 'locked', message: 'This is an approved policy decision and cannot be changed here.' });
  }
  const value = String(req.body?.value ?? '').trim();
  const bad = (m) => res.status(400).json({ error: 'validation', message: m });
  if (row.value_type === 'boolean' && !['true', 'false'].includes(value)) return bad('Choose true or false.');
  if (row.value_type === 'number' && !/^\d+$/.test(value)) return bad('Enter a whole number.');
  if (ENUMS[key] && !ENUMS[key].includes(value)) return bad(`Choose one of: ${ENUMS[key].join(', ')}.`);
  if (key === 'min_feedback_reveal_count' && Number(value) < 1) return bad('The threshold must be at least 1.');
  if (key === 'default_page_size' && ![25, 50, 100].includes(Number(value))) return bad('Page size must be 25, 50 or 100.');
  if (!value && row.value_type !== 'string') return bad('A value is required.');

  setSetting(key, value, req.user.id);
  audit(req, 'settings.changed', { entityType: 'setting', entityId: key, before: { value: row.value }, after: { value } });
  res.json({ ok: true });
});

/* ======================================================= 6.19 Analytics */

router.get('/analytics', (req, res) => {
  const awardType = ['Month', 'Year'].includes(req.query.awardType) ? req.query.awardType : null;
  const eligible = db.prepare(`SELECT COUNT(*) n FROM employees WHERE status='Active'`).get().n || 1;

  const participation = db.prepare(
    `SELECT c.id, c.award_type, c.period_label, c.status,
            (SELECT COUNT(*) FROM votes v WHERE v.cycle_id = c.id AND v.status='Submitted') AS voters
       FROM voting_cycles c
      WHERE c.status IN ${CLOSED.slice(0, -1)},'Open') AND (@t IS NULL OR c.award_type = @t)
      ORDER BY c.opens_at DESC LIMIT 12`
  ).all({ t: awardType }).reverse().map((c) => ({
    ...c, pretty_period: prettyPeriod(c), eligible, pct: Math.round((c.voters / eligible) * 100),
  }));

  const departments = db.prepare(
    `SELECT e.department,
            COUNT(*) AS headcount,
            SUM(CASE WHEN EXISTS (SELECT 1 FROM votes v JOIN voting_cycles c ON c.id = v.cycle_id
                                   WHERE v.voter_id = e.id AND v.status='Submitted' AND c.status IN ${CLOSED}
                                     AND (@t IS NULL OR c.award_type = @t)) THEN 1 ELSE 0 END) AS ever_voted,
            (SELECT COUNT(*) FROM votes v JOIN voting_cycles c ON c.id = v.cycle_id JOIN employees x ON x.id = v.voter_id
              WHERE x.department = e.department AND v.status='Submitted' AND c.status IN ${CLOSED}
                AND (@t IS NULL OR c.award_type = @t)) AS votes_cast,
            (SELECT ROUND(AVG(v.rating),2) FROM votes v JOIN voting_cycles c ON c.id = v.cycle_id JOIN employees x ON x.id = v.nominee_id
              WHERE x.department = e.department AND v.status='Submitted' AND c.status IN ${CLOSED}
                AND (@t IS NULL OR c.award_type = @t)) AS avg_rating_received,
            (SELECT COUNT(*) FROM winners w JOIN employees x ON x.id = w.employee_id JOIN voting_cycles c ON c.id = w.cycle_id
              WHERE x.department = e.department AND w.status='Published' AND (@t IS NULL OR c.award_type = @t)) AS awards
       FROM employees e WHERE e.status='Active' GROUP BY e.department ORDER BY e.department`
  ).all({ t: awardType });

  const distribution = Array.from({ length: 10 }, (_, i) => db.prepare(
    `SELECT COUNT(*) n FROM votes v JOIN voting_cycles c ON c.id = v.cycle_id
      WHERE v.status='Submitted' AND v.rating = ? AND c.status IN ${CLOSED} AND (@t IS NULL OR c.award_type = @t)`
  ).get(i + 1, { t: awardType }).n);

  // Department → department appreciation matrix (surfaces silos).
  const heat = db.prepare(
    `SELECT a.department AS from_dept, b.department AS to_dept, COUNT(*) n
       FROM votes v JOIN voting_cycles c ON c.id = v.cycle_id
       JOIN employees a ON a.id = v.voter_id JOIN employees b ON b.id = v.nominee_id
      WHERE v.status='Submitted' AND c.status IN ${CLOSED} AND (@t IS NULL OR c.award_type = @t)
      GROUP BY a.department, b.department`
  ).all({ t: awardType });

  const quality = db.prepare(
    `SELECT ROUND(AVG(LENGTH(v.reason_text) + LENGTH(v.comparison_text) + LENGTH(v.suggestion_text))) AS avg_len,
            SUM(v.flagged) AS flagged, COUNT(*) AS total
       FROM votes v JOIN voting_cycles c ON c.id = v.cycle_id
      WHERE v.status IN ('Submitted','RemovedByAdmin') AND c.status IN ${CLOSED} AND (@t IS NULL OR c.award_type = @t)`
  ).get({ t: awardType });

  // Non-voters in the live cycle — the one list HR actually acts on.
  const open = db.prepare(
    `SELECT * FROM voting_cycles WHERE status='Open' AND (@t IS NULL OR award_type = @t) ORDER BY closes_at LIMIT 1`
  ).get({ t: awardType });
  const nonVoters = open ? db.prepare(
    `SELECT e.employee_code, e.full_name, e.department FROM employees e
      WHERE e.status='Active' AND NOT EXISTS
            (SELECT 1 FROM votes v WHERE v.cycle_id = ? AND v.voter_id = e.id AND v.status='Submitted')
      ORDER BY e.department, e.full_name`
  ).all(open.id) : [];

  res.json({
    participation, departments, distribution, heat, quality,
    openCycle: open ? { id: open.id, pretty_period: prettyPeriod(open), award_type: open.award_type } : null,
    nonVoters,
  });
});

router.get('/analytics/participation.csv', (req, res) => {
  const rows = db.prepare(
    `SELECT c.award_type, c.period_label, c.status,
            (SELECT COUNT(*) FROM votes v WHERE v.cycle_id = c.id AND v.status='Submitted') AS voters
       FROM voting_cycles c WHERE c.status IN ${CLOSED.slice(0, -1)},'Open') ORDER BY c.opens_at DESC`
  ).all();
  const eligible = db.prepare(`SELECT COUNT(*) n FROM employees WHERE status='Active'`).get().n || 1;
  audit(req, 'report.exported', { entityType: 'report', entityId: 'participation' });
  sendCsv(res, 'participation.csv', toCsv({
    meta: [['Participation by cycle', ''], ['Generated by', req.user.full_name], ['Generated at (UTC)', new Date().toISOString()]],
    rows: rows.map((r) => ({ ...r, pretty: prettyPeriod(r), eligible, pct: Math.round((r.voters / eligible) * 100) })),
    columns: [
      { label: 'Award', key: 'award_type' }, { label: 'Period', key: 'pretty' }, { label: 'Status', key: 'status' },
      { label: 'Voters', key: 'voters' }, { label: 'Eligible (current)', key: 'eligible' }, { label: 'Participation %', key: 'pct' },
    ],
  }));
});
